"""create_games_table

Revision ID: 981b356a39d8
Revises: 
Create Date: 2025-05-20 00:27:43.771498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '981b356a39d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player1_token', sa.String(), nullable=True),
    sa.Column('player2_token', sa.String(), nullable=True),
    sa.Column('current_player_token', sa.String(), nullable=True),
    sa.Column('board_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('game_mode', sa.String(), nullable=False),
    sa.Column('winner_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_player1_token'), 'games', ['player1_token'], unique=False)
    op.create_index(op.f('ix_games_player2_token'), 'games', ['player2_token'], unique=False)
    op.create_index(op.f('ix_games_status'), 'games', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_status'), table_name='games')
    op.drop_index(op.f('ix_games_player2_token'), table_name='games')
    op.drop_index(op.f('ix_games_player1_token'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
