"""add_user_and_stats_tables_and_link_to_game

Revision ID: a7d30a422d08
Revises: 981b356a39d8
Create Date: 2025-06-06 18:27:35.055619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d30a422d08'
down_revision: Union[str, None] = '981b356a39d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('user_game_stats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('abandoned_by_user', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_game_stats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_game_stats'))
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player1_user_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('player2_user_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_games_player1_user_id'), ['player1_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_player2_user_id'), ['player2_user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_games_player1_user_id_users'), 'users', ['player1_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_games_player2_user_id_users'), 'users', ['player2_user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_games_player2_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_games_player1_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_games_player2_user_id'))
        batch_op.drop_index(batch_op.f('ix_games_player1_user_id'))
        batch_op.drop_column('player2_user_id')
        batch_op.drop_column('player1_user_id')

    op.drop_table('user_game_stats')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
